# wrangler.toml
# Replace "your-project-name" with a unique name for your Worker
name = "one-tools"
compatibility_date = "2025-05-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[site]
bucket = "./public"
entry-point = "functions" 